### ISSUE TITLE
Authorization for score download/upload accepts token with any scope

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/score#142]
Tested in SCORE QA environment for portal ego integration. (The download and upload scopes are configured to be scoreqa.READ/scoreqa.WRITE in this environment)

Steps to execute:

1. Create tokens in Token Manager for different scopes. 
2. When I pass tokens with scoreqa.READ/scoreqa.WRITE scopes, I am able to download (behaves as expected). 
3. When I pass ANY token which exists in Ego  (doesn't matter what the scope is) to SCORE, it also allows me to upload/download. 
4. However when I try and pass in  a garbage token, I get the response below:

![image](https://user-images.githubusercontent.com/12387683/54385363-c9f1f380-466c-11e9-9afe-e1ec53f3ea4d.png)
^ This error should be more informative and let me know that the token is invalid .

**Comment by KevinFHartmann** [comment]
Findings: 
1) The reason any valid Ego token works is that the file has open access.
2) The reason the ugly error message appears is because it's trying to parse a HTML error message as if it were JSON, and failing. 
3) SONG shouldn't give HTML error messages; and score-client shouldn't choke on them.

**Comment by alekspejovic** [comment]
Two new tickets opened up to fix error messages in SONG & SCORE:

1. https://github.com/overture-stack/SONG/issues/402
2. https://github.com/overture-stack/score/issues/143
