### ISSUE TITLE
resume downloading feature in score-client

### ISSUE THREAD

**Issue by hknahal** [overture-stack/score#151]
This issue was brought up by a user recently (see comment [here](https://extsd.oicr.on.ca/browse/ICGCSD-2777?focusedCommentId=17091&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel%5C#comment-17091)). Whenever Collaboratory goes offline (ie. for maintenance), any active downloads using score-client will obviously fail. But once Collaboratory is back online, the user tries to resume downloading but the score-client errors out when it encounters a file that has already been downloaded. Here's an example error message:

```ERROR: Bad parameter(s): Download file 'score-client_downloads/7bdcb78a-c623-11e3-bf01-24c6515278c0.consensus.20161006.somatic.indel.vcf.gz.tbi' already exists and --force was not specified```

Instead of failing, is it possible to just skip over the existing downloaded file(s) and continue downloading the other remaining files?

**Comment by KevinFHartmann** [comment]
After discussion with Hardeep, the specification for how the downloads should be resumed is as follows:

(1) If the user specifies -f (force), then score-client will delete all previously downloaded files and download everything from scratch.
(2) Otherwise, for each file to be downloaded, the score-client will:
     (a) if the existing file is shorter than the file is supposed to be, resume downloading starting from the length of the existing file. When the file download is complete, do an md5 check. If it fails, delete the file, and download the entire file from scratch.
    (b)If it’s longer than the manifest says it should be, or the right size with the wrong md5, download from scratch.
(3) If a file is downloaded from scratch, and the md5 is still wrong, print a warning message.

We currently do have some otherwise valid files in Collaboratory with md5s that don't match. They're supposed to be fixed soon.
